/**
 * lib/services/research.service.ts
 *
 * Research Service — the single orchestration layer between API routes and the AI module.
 *
 * Responsibilities:
 *  1. Create a research session row (status: idle).
 *  2. Update session to 'running' before graph execution.
 *  3. Invoke runResearchGraph() from lib/ai/graph.ts (UNTOUCHED).
 *  4. Persist every AgentEvent to agent_logs in real-time.
 *  5. Stream each AgentEvent to the SSE controller.
 *  6. On graph completion: persist sources, claims, contradictions, and final session state.
 *  7. On failure: set session status to 'failed' and stream an ERROR event.
 *
 * The AI module (lib/ai/*) is never imported for modification — only consumed.
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import { ResearchRepository } from '@/lib/db/repository';
import { runResearchGraph } from '@/lib/ai/graph';
import type { AgentEvent } from '@/lib/ai/types';
import {
  encodeAgentEvent,
  encodeCompleteEvent,
  encodeErrorEvent,
} from '@/lib/backend/sse';
import type { ResearchSessionRow } from '@/lib/db/types';

// ── Types ─────────────────────────────────────────────────────────────────────

/** Callback signature passed to executeResearch for SSE streaming. */
export type SSEWriter = (chunk: Uint8Array) => void;

export interface CreateSessionResult {
  session: ResearchSessionRow;
}

// ── Service Functions ─────────────────────────────────────────────────────────

/**
 * Creates a new research session row in the database with status='idle'.
 * Called from POST /api/research before returning the 201 response.
 *
 * @param supabase - Server-side Supabase client (carries user auth context).
 * @param userId   - Authenticated user's UUID.
 * @param sessionId - UUID generated by the API route.
 * @param question  - The research question from the request body.
 */
export async function createResearchSession(
  supabase: SupabaseClient,
  userId: string,
  sessionId: string,
  question: string
): Promise<CreateSessionResult> {
  const repo = new ResearchRepository(supabase);

  const session = await repo.createSession({
    session_id: sessionId,
    user_id: userId,
    question,
  });

  return { session };
}

/**
 * Executes the research graph for an existing session and streams results.
 * Called from GET /api/research/[sessionId]/stream.
 *
 * Flow:
 *  - Update session: idle → running.
 *  - Invoke runResearchGraph with onAgentEvent callback.
 *  - Each event: insert to agent_logs + write to SSE stream.
 *  - On success: persist all results + update session → completed.
 *  - On failure: update session → failed + stream ERROR event.
 *
 * @param supabase   - Server-side Supabase client (carries user auth context).
 * @param sessionId  - The string session key used throughout the pipeline.
 * @param question   - The research question for the AI graph.
 * @param sseWriter  - Callback that enqueues Uint8Array chunks into the ReadableStream.
 */
export async function executeResearch(
  supabase: SupabaseClient,
  sessionId: string,
  question: string,
  sseWriter: SSEWriter
): Promise<void> {
  const repo = new ResearchRepository(supabase);

  // ── 1. Mark session as running ────────────────────────────────────────────
  await repo.updateSessionStatus(sessionId, 'running');

  // ── 2. Define the real-time event callback ────────────────────────────────
  const onAgentEvent = async (event: AgentEvent): Promise<void> => {
    // Persist log to DB (swallows errors internally — log failures must not crash graph)
    await repo.insertAgentLog({
      session_id: sessionId,
      agent_name: event.agentName,
      status: event.status,
      message: event.message,
      output_data: (event.outputData as Record<string, unknown>) ?? null,
      duration_ms: event.durationMs ?? null,
    });

    // Stream the event to the SSE client
    try {
      sseWriter(
        encodeAgentEvent({
          sessionId: event.sessionId,
          agentName: event.agentName,
          status: event.status,
          message: event.message,
          outputData: event.outputData as Record<string, unknown> | undefined,
          durationMs: event.durationMs,
        })
      );
    } catch (sseErr) {
      // Client may have disconnected — log and continue (graph runs to completion)
      console.warn('[ResearchService] SSE write failed (client may have disconnected):', sseErr);
    }
  };

  // ── 3. Invoke the AI graph ────────────────────────────────────────────────
  try {
    const finalState = await runResearchGraph(sessionId, question, { onAgentEvent });

    // ── 4. Persist child records ─────────────────────────────────────────────

    // Sources — idempotent upsert handles retry-loop duplicates
    if (finalState.sources.length > 0) {
      await repo.bulkInsertSources(finalState.sources, sessionId);
    }

    // Claims — idempotent upsert
    if (finalState.claims.length > 0) {
      await repo.bulkInsertClaims(finalState.claims, sessionId);
    }

    // Contradictions — insert (contradictions are not expected to be duplicated)
    if (finalState.contradictions.length > 0) {
      await repo.bulkInsertContradictions(finalState.contradictions, sessionId);
    }

    // ── 5. Mark session as completed ─────────────────────────────────────────
    await repo.completeSession(sessionId, {
      status: 'completed',
      retry_count: finalState.retryCount,
      research_objectives: finalState.researchObjectives.length > 0
        ? finalState.researchObjectives
        : null,
      research_notes: finalState.researchNotes || null,
      confidence_score: finalState.confidenceScore,
      confidence_reasoning: finalState.confidenceReasoning
        ? {
            score: finalState.confidenceReasoning.score,
            reason: finalState.confidenceReasoning.reason,
            supportingFactors: finalState.confidenceReasoning.supportingFactors ?? [],
            detractingFactors: finalState.confidenceReasoning.detractingFactors ?? [],
          }
        : null,
      final_report: finalState.finalReport || null,
    });

    // ── 6. Send COMPLETE event to client ──────────────────────────────────────
    try {
      sseWriter(
        encodeCompleteEvent({ sessionId, status: 'completed' })
      );
    } catch {
      // Client disconnected before COMPLETE — results are persisted, ignore
    }

    console.log(`[ResearchService] Session ${sessionId} completed successfully.`);
  } catch (graphError) {
    // ── 7. Handle graph failure ───────────────────────────────────────────────
    const errorMessage =
      graphError instanceof Error ? graphError.message : 'Unknown graph error';

    console.error(`[ResearchService] Session ${sessionId} failed:`, graphError);

    // Persist failure status
    try {
      await repo.completeSession(sessionId, {
        status: 'failed',
        retry_count: 0,
        research_objectives: null,
        research_notes: null,
        confidence_score: null,
        confidence_reasoning: null,
        final_report: null,
      });
    } catch (dbErr) {
      console.error('[ResearchService] Failed to mark session as failed in DB:', dbErr);
    }

    // Stream ERROR event to client
    try {
      sseWriter(
        encodeErrorEvent({ sessionId, status: 'failed', error: errorMessage })
      );
    } catch {
      // Client disconnected — ignore
    }

    // Re-throw so the stream controller can close cleanly
    throw graphError;
  }
}
