import { AgentInfo, AgentId } from './types';

export const AGENT_OUTPUTS: Record<AgentId, string[]> = {
  orchestrator: [
    'Parsed user intent: multi-domain factual inquiry requiring cross-source verification.',
    'Initialized execution graph with 9 specialized agent nodes.',
    'Delegated Task 1 to Research Strategist for sub-objective decomposition.',
    'Monitoring pipeline confidence gate: threshold set at 80% for report generation.',
    'All downstream agents synchronized. Orchestration complete in 412ms.',
  ],
  strategist: [
    'Decomposed question into 4 orthogonal research vectors:',
    '  [1] Metabolic & glycemic effects of TRE in human RCTs',
    '  [2] Body composition and lean mass outcomes',
    '  [3] Cardiovascular biomarker changes',
    '  [4] Longevity mechanisms (autophagy, mTOR, AMPK pathways)',
    'Generated 12 targeted search queries across 3 academic databases.',
    'Strategy handoff to Search Specialist: ETA 1.2s.',
  ],
  search: [
    'Queried Tavily Search API → 200 OK, 14 URLs retrieved in 820ms.',
    'Queried PubMed E-utilities → 6 peer-reviewed abstracts fetched.',
    'Queried arXiv (q-bio.MN) → 2 preprints returned.',
    'Prioritized sources by domain authority:',
    '  ★★★ NEJM, Cell Metabolism, JAMA Internal Medicine, NIH.gov',
    '  ★★  Harvard Health, Mayo Clinic',
    'Deduplicated 22 raw results → 14 unique authoritative documents.',
  ],
  analyst: [
    'Processed 14 source documents (avg 4,200 tokens each).',
    'Extracted key statistical findings:',
    '  • NEJM 2023: IF broadly effective across obesity, diabetes, CVD',
    '  • Cell Metabolism 2024: TRE 16:8 ↓ HbA1c, ↓ systolic BP (p<0.01)',
    '  • NIH Meta-Analysis: No significant difference vs. continuous CR at 12 months',
    '  • JAMA 2023: 65% lean mass loss in sedentary IF group (no resistance training)',
    'Compiled 3,400-word structured research notes. Handing off to Evidence Analyst.',
  ],
  evidence: [
    'Extracted 6 atomic, independently verifiable claims from research notes:',
    '  [CLAIM-01] IF improves glycemic control in prediabetic adults (HbA1c reduction)',
    '  [CLAIM-02] TRE reduces systolic blood pressure independently of calorie counting',
    '  [CLAIM-03] IF is superior to calorie restriction for total weight loss',
    '  [CLAIM-04] IF triggers autophagy and extends human lifespan',
    '  [CLAIM-05] Lean muscle loss risk increases without resistance training',
    '  [CLAIM-06] 16:8 TRE improves metabolic flexibility and fat oxidation',
    'Claims formatted as structured JSON with source attribution.',
  ],
  verifier: [
    'Verifying CLAIM-01 → Corroborated by NEJM 2023 & Cell Metabolism 2024 → STATUS: VERIFIED ✅',
    'Verifying CLAIM-02 → Corroborated by Cell Metabolism RCT (p<0.001) → STATUS: VERIFIED ✅',
    'Verifying CLAIM-03 → NIH meta-analysis contradicts this claim → STATUS: MIXED EVIDENCE ⚠',
    'Verifying CLAIM-04 → Animal models support, human longitudinal data absent → STATUS: UNSUPPORTED ❌',
    'Verifying CLAIM-05 → JAMA 2023 confirms lean loss without resistance exercise → STATUS: VERIFIED ✅',
    'Verifying CLAIM-06 → Cell Metabolism 2024 supports mechanistic pathway → STATUS: VERIFIED ✅',
    '4 of 6 claims verified. 1 mixed evidence. 1 unsupported.',
  ],
  contradiction: [
    'Scanning for adversarial evidence and methodological discrepancies...',
    'CONTRADICTION DETECTED — Lean Muscle Preservation:',
    '  Source A (Cell Metabolism 2024): Muscle mass maintained with protein pairing.',
    '  Source B (JAMA Int Med 2023): 65% weight loss was lean mass in sedentary subjects.',
    '  Root Cause: Exercise control condition absent in Cell Metabolism trial.',
    'CLAIM-03 conflict: NIH meta-analysis (n=18 RCTs) shows null superiority vs. CICO.',
    'Confidence impact: −15 points applied for methodological discrepancy in muscle data.',
  ],
  scorer: [
    'Computing explainable confidence score...',
    '  Base Certainty Score:        +50',
    '  Trusted Source Bonus:        +30  (3× high-authority domains)',
    '  Peer-Reviewed Bonus:         +20  (NEJM + Cell Metabolism)',
    '  Contradiction Penalty:       −15  (lean mass exercise discrepancy)',
    '  ─────────────────────────────────',
    '  FINAL CONFIDENCE SCORE:       85%  (HIGH CONFIDENCE)',
    'Score clamped to [0, 100]. No single-source penalty applied.',
    'Confidence gate: PASSED. Routing to Report Writer.',
  ],
  writer: [
    'Assembling transparent evidence-backed research report...',
    'Executive Summary: 320 words generated.',
    'Claim section: 6 claims with status badges and citation indices.',
    'Contradiction section: 1 contradiction with methodology analysis.',
    'Recommendations: 3 evidence-based action items generated.',
    'Reference list: 4 primary sources with DOIs and credibility scores.',
    'Report Writer complete. Final document ready for export.',
  ],
};
