import { AgentInfo, PresetQuery, ResearchReport, Source, Claim, Contradiction, ConfidenceBreakdown, TimelineEvent, LogEntry } from './types';

export const INITIAL_AGENTS: AgentInfo[] = [
  {
    id: 'orchestrator',
    name: 'Orchestrator',
    role: 'Central Workflow Controller',
    icon: '🧠',
    description: 'Coordinates multi-agent workflow, delegates tasks, monitors confidence, and manages retries.',
    status: 'idle',
    currentTask: 'Awaiting user question...',
    progress: 0,
    durationMs: 0,
    outputSummary: 'Ready to coordinate execution strategy.',
  },
  {
    id: 'strategist',
    name: 'Research Strategist',
    role: 'Decomposition Specialist',
    icon: '🗺',
    description: 'Decomposes complex questions into structured research sub-objectives and search vectors.',
    status: 'idle',
    currentTask: 'Pending orchestration...',
    progress: 0,
    durationMs: 0,
    outputSummary: 'Awaiting research breakdown.',
  },
  {
    id: 'search',
    name: 'Search Specialist',
    role: 'Source Discovery Agent',
    icon: '🔍',
    description: 'Queries Tavily, Firecrawl, arXiv, PubMed, and government databases for authoritative sources.',
    status: 'idle',
    currentTask: 'Pending discovery...',
    progress: 0,
    durationMs: 0,
    outputSummary: 'Awaiting search terms.',
  },
  {
    id: 'analyst',
    name: 'Research Analyst',
    role: 'Synthesis & Document Reader',
    icon: '📚',
    description: 'Reads full text, extracts key findings, extracts statistical figures, and builds research notes.',
    status: 'idle',
    currentTask: 'Pending reading...',
    progress: 0,
    durationMs: 0,
    outputSummary: 'Awaiting source documents.',
  },
  {
    id: 'evidence',
    name: 'Evidence Analyst',
    role: 'Atomic Claim Extractor',
    icon: '📝',
    description: 'Converts unstructured research notes into discrete, independently testable atomic claims.',
    status: 'idle',
    currentTask: 'Pending extraction...',
    progress: 0,
    durationMs: 0,
    outputSummary: 'Awaiting synthesized notes.',
  },
  {
    id: 'verifier',
    name: 'Verification Specialist',
    role: 'Cross-Source Fact Checker',
    icon: '✅',
    description: 'Verifies extracted claims against independent primary sources and checks publication authority.',
    status: 'idle',
    currentTask: 'Pending verification...',
    progress: 0,
    durationMs: 0,
    outputSummary: 'Awaiting atomic claims.',
  },
  {
    id: 'contradiction',
    name: 'Contradiction Detector',
    role: 'Adversarial Challenger',
    icon: '⚔',
    description: 'Actively searches for conflicting data, methodologies, or opposing literature to challenge claims.',
    status: 'idle',
    currentTask: 'Pending conflict search...',
    progress: 0,
    durationMs: 0,
    outputSummary: 'Awaiting claim evaluation.',
  },
  {
    id: 'scorer',
    name: 'Confidence Scorer',
    role: 'Algorithmic Trust Evaluator',
    icon: '📊',
    description: 'Applies explainable mathematical scoring based on source authority, consensus, and contradiction penalties.',
    status: 'idle',
    currentTask: 'Pending evaluation...',
    progress: 0,
    durationMs: 0,
    outputSummary: 'Awaiting verification metrics.',
  },
  {
    id: 'writer',
    name: 'Report Writer',
    role: 'Transparent Synthesis Generator',
    icon: '📄',
    description: 'Assembles transparent, citation-backed final research report with clear executive summary & recommendations.',
    status: 'idle',
    currentTask: 'Pending final draft...',
    progress: 0,
    durationMs: 0,
    outputSummary: 'Awaiting scored dataset.',
  },
];

export const PRESET_QUERIES: PresetQuery[] = [
  {
    id: 'intermittent-fasting',
    title: 'Intermittent Fasting',
    question: 'Should I trust intermittent fasting for weight loss and longevity?',
    category: 'Health & Biology',
    report: {
      id: 'rep-if-01',
      query: 'Should I trust intermittent fasting for weight loss and longevity?',
      timestamp: 'Just now',
      overallConfidence: {
        baseScore: 50,
        trustedSourceBonus: 30, // 3 trusted sources
        peerReviewedBonus: 20, // New England Journal of Medicine & Cell Metabolism
        contradictionPenalty: -15, // Human vs mouse study discrepancy
        singleSourcePenalty: 0,
        finalScore: 85,
        explanation: 'Strong peer-reviewed consensus for metabolic health and glycemic control (+50 points). However, human trial longevity data remains inconclusive (-15 points contradiction penalty).',
      },
      executiveSummary:
        'Intermittent Fasting (IF), specifically Time-Restricted Eating (TRE 16:8), is clinically validated to improve insulin sensitivity, reduce visceral fat, and promote autophagy in mammalian models. While human trials confirm robust short-term cardiometabolic benefits equivalent to continuous calorie restriction, long-term human life-extension claims rely primarily on mechanistic animal proxies. Minor contradictions exist regarding lean muscle retention in older adults without resistance training.',
      sources: [
        {
          id: 'src-1',
          title: 'Effects of Intermittent Fasting on Health, Aging, and Disease',
          url: 'https://www.nejm.org/doi/full/10.1056/NEJMra1905136',
          domain: 'nejm.org',
          authoritativeness: 'high',
          type: 'peer-reviewed',
          snippet: 'Preclinical studies and clinical trials have shown that intermittent fasting has broad-spectrum benefits for health conditions such as obesity, diabetes mellitus, cardiovascular disease, and neurological disorders.',
          publishDate: '2023-11-15',
          credibilityScore: 98,
        },
        {
          id: 'src-2',
          title: 'Time-Restricted Eating in Humans: Metabolic and Cellular Mechanisms',
          url: 'https://www.cell.com/cell-metabolism/fulltext/S1550-4131(22)00492-X',
          domain: 'cell.com',
          authoritativeness: 'high',
          type: 'peer-reviewed',
          snippet: 'Randomized controlled trial of 16:8 TRE demonstrated significant reductions in HbA1c, systolic blood pressure, and systemic inflammatory markers (CRP) independent of calorie counting.',
          publishDate: '2024-02-10',
          credibilityScore: 95,
        },
        {
          id: 'src-3',
          title: 'Caloric Restriction vs. Intermittent Fasting for Weight Loss: A Meta-Analysis',
          url: 'https://www.nih.gov/news-events/nih-research-matters/intermittent-fasting-weight-loss',
          domain: 'nih.gov',
          authoritativeness: 'high',
          type: 'government',
          snippet: 'Meta-analysis of 18 human RCTs found no statistically significant difference in total fat mass reduction between intermittent fasting and daily continuous calorie restriction over 12 months.',
          publishDate: '2024-05-01',
          credibilityScore: 96,
        },
        {
          id: 'src-4',
          title: 'Evaluation of Lean Mass Retention During 16:8 Fasting Regimens',
          url: 'https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2771095',
          domain: 'jamanetwork.com',
          authoritativeness: 'high',
          type: 'peer-reviewed',
          snippet: 'A 12-week randomized trial observed greater loss of lean appendicular mass in fasting groups who did not participate in resistance training.',
          publishDate: '2023-08-22',
          credibilityScore: 92,
        },
      ],
      verifiedClaims: [
        {
          id: 'cl-1',
          statement: 'Intermittent fasting improves glycemic control and reduces HbA1c in prediabetic and diabetic adults.',
          status: 'verified',
          confidenceScore: 96,
          reasoning: 'Confirmed by multiple independent randomized controlled trials (NEJM 2023, Cell Metabolism 2024). High effect size across diverse human demographics.',
          supportingSourceIds: ['src-1', 'src-2'],
          conflictingSourceIds: [],
          keyQuotes: [
            'Preclinical studies and clinical trials have shown that intermittent fasting has broad-spectrum benefits for diabetes mellitus.',
            'Randomized controlled trial of 16:8 TRE demonstrated significant reductions in HbA1c.',
          ],
          extractedByAgent: 'Evidence Analyst',
        },
        {
          id: 'cl-2',
          statement: 'Intermittent fasting is superior to traditional calorie restriction for total weight loss.',
          status: 'mixed',
          confidenceScore: 62,
          reasoning: 'Conflicting conclusions between popular media claims and NIH meta-analysis. Weight loss efficacy is identical when overall calorie intake is matched.',
          supportingSourceIds: ['src-2'],
          conflictingSourceIds: ['src-3'],
          keyQuotes: [
            'Meta-analysis of 18 human RCTs found no statistically significant difference in total fat mass reduction between intermittent fasting and daily continuous calorie restriction.',
          ],
          extractedByAgent: 'Evidence Analyst',
        },
        {
          id: 'cl-3',
          statement: 'Time-Restricted Eating triggers neuronal autophagy and extends maximum human lifespan.',
          status: 'unsupported',
          confidenceScore: 41,
          reasoning: 'Autophagy marker upregulation is well-established in murine models, but longitudinal human evidence for lifespan extension is lacking.',
          supportingSourceIds: ['src-1'],
          conflictingSourceIds: ['src-3'],
          keyQuotes: [
            'Human trials confirm robust short-term cardiometabolic benefits, but long-term human life-extension claims rely primarily on animal proxies.',
          ],
          extractedByAgent: 'Evidence Analyst',
        },
      ],
      contradictions: [
        {
          id: 'cnt-1',
          topic: 'Lean Muscle Preservation',
          claimA: 'Cell Metabolism trial reports muscle mass retention under 16:8 fasting with protein pairing.',
          sourceAId: 'src-2',
          claimB: 'JAMA Internal Medicine study shows 65% of weight lost without resistance exercise was lean muscle mass.',
          sourceBId: 'src-4',
          explanation: 'Discrepancy stems from resistance exercise controls. Fasting without resistance training risks muscle atrophy in sedentary populations.',
          impactOnConfidence: -15,
        },
      ],
      recommendations: [
        'Adopt 16:8 Time-Restricted Eating if adherence to traditional daily calorie restriction is challenging.',
        'Pair intermittent fasting with resistance exercise (2-3x weekly) and adequate protein intake (1.6g/kg) to protect appendicular muscle mass.',
        'Consult a physician prior to starting IF if diagnosed with Type 1 Diabetes or taking blood glucose-lowering medication.',
      ],
      methodologyNotes: 'Orchestrator queried 4 primary databases, extracted 12 atomic claims, verified 4 sources, and flagged 1 critical methodological contradiction regarding exercise controls.',
    },
  },
  {
    id: 'ai-regulations',
    title: 'AI Regulations',
    question: 'What are the global compliance requirements under the EU AI Act and US Executive Orders?',
    category: 'Policy & Technology',
    report: {
      id: 'rep-ai-02',
      query: 'What are the global compliance requirements under the EU AI Act and US Executive Orders?',
      timestamp: '5 mins ago',
      overallConfidence: {
        baseScore: 50,
        trustedSourceBonus: 30,
        peerReviewedBonus: 20,
        contradictionPenalty: 0,
        singleSourcePenalty: 0,
        finalScore: 94,
        explanation: 'Extremely high legal consensus from official EU Parliament publications and NIST safety frameworks (+44 points). No direct regulatory contradictions identified.',
      },
      executiveSummary:
        'The global AI regulatory environment has transitioned from voluntary frameworks to legally binding enforcement. The EU AI Act enforces a strict risk-tiered model (Unacceptable, High, General Purpose AI, Limited Risk) with fines up to €35M or 7% of global annual turnover. Simultaneously, US Executive Order 14110 mandates red-teaming safety disclosures to the Department of Commerce for foundation models trained on >10^26 FLOPs.',
      sources: [
        {
          id: 'src-ai-1',
          title: 'Official Regulation (EU) 2024/1689 laying down harmonised rules on Artificial Intelligence',
          url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689',
          domain: 'eur-lex.europa.eu',
          authoritativeness: 'high',
          type: 'government',
          snippet: 'Establishes obligations for providers and deployers of high-risk AI systems including risk management systems, data governance, technical documentation, and human oversight.',
          publishDate: '2024-07-12',
          credibilityScore: 100,
        },
        {
          id: 'src-ai-2',
          title: 'NIST AI Risk Management Framework (AI RMF 1.0) Implementation Guide',
          url: 'https://www.nist.gov/itl/ai-risk-management-framework',
          domain: 'nist.gov',
          authoritativeness: 'high',
          type: 'government',
          snippet: 'Provides actionable guidelines for mapping, measuring, managing, and governing AI risks across enterprise lifecycles.',
          publishDate: '2024-01-20',
          credibilityScore: 97,
        },
        {
          id: 'src-ai-3',
          title: 'US Executive Order 14110: Safe, Secure, and Trustworthy Development and Use of Artificial Intelligence',
          url: 'https://www.whitehouse.gov/briefing-room/presidential-actions/2023/10/30/executive-order-14110',
          domain: 'whitehouse.gov',
          authoritativeness: 'high',
          type: 'government',
          snippet: 'Requires developers of dual-use foundation models to share safety test results and red-teaming documentation with the US government.',
          publishDate: '2023-10-30',
          credibilityScore: 99,
        },
      ],
      verifiedClaims: [
        {
          id: 'cl-ai-1',
          statement: 'High-risk AI systems deployed in the EU must maintain continuous risk management systems and conform to strict data governance.',
          status: 'verified',
          confidenceScore: 99,
          reasoning: 'Direct legal text from EU AI Act Article 9 & Article 10. Binding law across all 27 EU member states.',
          supportingSourceIds: ['src-ai-1'],
          conflictingSourceIds: [],
          keyQuotes: [
            'Establishes obligations for providers and deployers of high-risk AI systems including risk management systems, data governance, technical documentation, and human oversight.',
          ],
          extractedByAgent: 'Evidence Analyst',
        },
        {
          id: 'cl-ai-2',
          statement: 'US AI safety requirements apply to any model trained using more than 10^26 floating-point operations (FLOPs).',
          status: 'verified',
          confidenceScore: 95,
          reasoning: 'Explicit computing threshold specified in US EO 14110 Section 4.2.',
          supportingSourceIds: ['src-ai-3'],
          conflictingSourceIds: [],
          keyQuotes: [
            'Requires developers of dual-use foundation models to share safety test results.',
          ],
          extractedByAgent: 'Evidence Analyst',
        },
      ],
      contradictions: [],
      recommendations: [
        'Perform a system audit to classify all internal AI workloads according to the EU AI Act risk tiers.',
        'Implement automated logging and human-in-the-loop oversight mechanisms for high-risk employment or credit evaluation pipelines.',
        'Establish NIST AI RMF compliance mapping for US market operations.',
      ],
      methodologyNotes: 'Analyzed official treaty documents, statutory texts, and government publications across EU and US jurisdiction.',
    },
  },
  {
    id: 'climate-consensus',
    title: 'Climate Change Consensus',
    question: 'What is the current scientific consensus on human-driven climate change and tipping points?',
    category: 'Earth & Environmental Science',
    report: {
      id: 'rep-cc-03',
      query: 'What is the current scientific consensus on human-driven climate change and tipping points?',
      timestamp: '15 mins ago',
      overallConfidence: {
        baseScore: 50,
        trustedSourceBonus: 30,
        peerReviewedBonus: 20,
        contradictionPenalty: 0,
        singleSourcePenalty: 0,
        finalScore: 98,
        explanation: 'Overwhelming scientific consensus (>99.3% peer-reviewed agreement) supported by IPCC AR6, NASA Earth Science, and Nature Climate Change.',
      },
      executiveSummary:
        'There is definitive scientific consensus (>99% of peer-reviewed climate science literature) that human activity, primarily fossil fuel combustion and deforestation, is warming the Earth system at an unprecedented rate in at least the last 2,000 years. Global mean surface temperatures have reached 1.15°C–1.25°C above pre-industrial baselines. Crucial tipping points—including the collapse of the Atlantic Meridional Overturning Circulation (AMOC) and West Antarctic Ice Sheet destabilization—exhibit rising probability under sustained warming above 1.5°C.',
      sources: [
        {
          id: 'src-cc-1',
          title: 'IPCC Sixth Assessment Report (AR6): The Physical Science Basis',
          url: 'https://www.ipcc.ch/report/ar6/wg1/',
          domain: 'ipcc.ch',
          authoritativeness: 'high',
          type: 'government',
          snippet: 'It is unequivocal that human influence has warmed the atmosphere, ocean and land. Widespread and rapid changes in the atmosphere, ocean, cryosphere and biosphere have occurred.',
          publishDate: '2023-03-20',
          credibilityScore: 99,
        },
        {
          id: 'src-cc-2',
          title: 'Greater than 99% consensus on human caused climate change in peer-reviewed scientific literature',
          url: 'https://iopscience.iop.org/article/10.1088/1748-9326/ac2966',
          domain: 'iopscience.iop.org',
          authoritativeness: 'high',
          type: 'peer-reviewed',
          snippet: 'Survey of 88,125 climate-related studies finds that over 99.9% of peer-reviewed scientific papers agree that climate change is mainly caused by humans.',
          publishDate: '2023-10-19',
          credibilityScore: 97,
        },
      ],
      verifiedClaims: [
        {
          id: 'cl-cc-1',
          statement: 'Human influence on the Earth’s climate system is scientifically unequivocal.',
          status: 'verified',
          confidenceScore: 99,
          reasoning: 'Formally endorsed by 195 IPCC member nations and backed by thousands of independent paleoclimate and satellite observation datasets.',
          supportingSourceIds: ['src-cc-1', 'src-cc-2'],
          conflictingSourceIds: [],
          keyQuotes: [
            'It is unequivocal that human influence has warmed the atmosphere, ocean and land.',
          ],
          extractedByAgent: 'Evidence Analyst',
        },
      ],
      contradictions: [],
      recommendations: [
        'Prioritize deep decarbonization pathways targeting 45% emissions reduction by 2030.',
        'Invest in climate adaptation infrastructure for high-risk coastal and agricultural regions.',
      ],
      methodologyNotes: 'Cross-referenced IPCC Working Group I findings with independent peer-reviewed literature surveys.',
    },
  },
  {
    id: 'quantum-computing',
    title: 'Quantum Computing',
    question: 'What is quantum computing and when will post-quantum cryptography be required?',
    category: 'Physics & Computing',
    report: {
      id: 'rep-qc-04',
      query: 'What is quantum computing and when will post-quantum cryptography be required?',
      timestamp: '1 hour ago',
      overallConfidence: {
        baseScore: 50,
        trustedSourceBonus: 30,
        peerReviewedBonus: 20,
        contradictionPenalty: -10,
        singleSourcePenalty: 0,
        finalScore: 88,
        explanation: 'Strong consensus on physics fundamentals and NIST post-quantum standardization (+50 points). Minor variance on hardware fault-tolerance timelines (-10 points).',
      },
      executiveSummary:
        'Quantum computing utilizes quantum mechanical phenomena—superposition, entanglement, and quantum interference—to perform specific calculations exponentially faster than classical supercomputers. While fault-tolerant quantum computers capable of breaking RSA-2048 encryption using Shor’s algorithm are estimated to be 10–15 years away, NIST released its first official Post-Quantum Cryptography (PQC) standards (ML-KEM, ML-DSA) in August 2024. Organizations are advised to initiate "Harvest Now, Decrypt Later" defense immediately.',
      sources: [
        {
          id: 'src-qc-1',
          title: 'NIST Releases First Official Post-Quantum Cryptography Standards',
          url: 'https://www.nist.gov/news-events/news/2024/08/nist-releases-first-official-post-quantum-encryption-standards',
          domain: 'nist.gov',
          authoritativeness: 'high',
          type: 'government',
          snippet: 'NIST has finalized its principal set of encryption algorithms designed to withstand cyberattacks from future quantum computers.',
          publishDate: '2024-08-13',
          credibilityScore: 99,
        },
      ],
      verifiedClaims: [
        {
          id: 'cl-qc-1',
          statement: 'NIST has finalized official Post-Quantum Cryptography standards to replace RSA and ECC algorithms.',
          status: 'verified',
          confidenceScore: 98,
          reasoning: 'Official government publication released August 13, 2024 introducing FIPS 203, 204, and 205.',
          supportingSourceIds: ['src-qc-1'],
          conflictingSourceIds: [],
          keyQuotes: [
            'NIST has finalized its principal set of encryption algorithms designed to withstand cyberattacks from future quantum computers.',
          ],
          extractedByAgent: 'Evidence Analyst',
        },
      ],
      contradictions: [],
      recommendations: [
        'Inventory all public-key cryptography implementations across enterprise applications.',
        'Begin migrating sensitive long-life encrypted assets to NIST FIPS 203 (ML-KEM) standard.',
      ],
      methodologyNotes: 'Queried NIST PQC guidelines, IEEE Quantum Engineering proceedings, and ACM computing surveys.',
    },
  },
];

export function generateDynamicReport(query: string): ResearchReport {
  return {
    id: `rep-dyn-${Date.now()}`,
    query,
    timestamp: 'Just now',
    overallConfidence: {
      baseScore: 50,
      trustedSourceBonus: 30,
      peerReviewedBonus: 20,
      contradictionPenalty: -10,
      singleSourcePenalty: 0,
      finalScore: 90,
      explanation: 'Verified against 5 high-authority peer-reviewed and academic literature sources (+50 points). Minor contextual nuances flagged (-10 points).',
    },
    executiveSummary: `Veritas AI executed a multi-agent verification pipeline on "${query}". The research team decomposed the inquiry into 4 distinct factual sub-domains, retrieved 14 primary sources, and extracted 6 independently verifiable claims. Overall evidence strongly supports positive conclusions with high scientific precision.`,
    sources: [
      {
        id: 'src-dyn-1',
        title: `Comprehensive Analysis of ${query}`,
        url: 'https://nature.com/articles/s41586-2024-001',
        domain: 'nature.com',
        authoritativeness: 'high',
        type: 'peer-reviewed',
        snippet: `Peer-reviewed meta-analysis examining primary evidence, quantitative findings, and long-term implications regarding ${query}.`,
        publishDate: '2024-06-15',
        credibilityScore: 97,
      },
      {
        id: 'src-dyn-2',
        title: `Government Policy & Safety Framework for ${query}`,
        url: 'https://gov.research.org/reports/2024',
        domain: 'gov.research.org',
        authoritativeness: 'high',
        type: 'government',
        snippet: `Official governmental research findings providing structured guidance and consensus metrics on ${query}.`,
        publishDate: '2024-04-10',
        credibilityScore: 94,
      },
    ],
    verifiedClaims: [
      {
        id: 'cl-dyn-1',
        statement: `Primary empirical evidence confirms high statistical backing for ${query.substring(0, 45)}...`,
        status: 'verified',
        confidenceScore: 94,
        reasoning: 'Corroborated by independent Nature meta-analysis and government data repos.',
        supportingSourceIds: ['src-dyn-1', 'src-dyn-2'],
        conflictingSourceIds: [],
        keyQuotes: [
          `Peer-reviewed meta-analysis examining primary evidence regarding ${query}.`,
        ],
        extractedByAgent: 'Evidence Analyst',
      },
      {
        id: 'cl-dyn-2',
        statement: `Secondary factors require contextual qualification depending on operational environments.`,
        status: 'mixed',
        confidenceScore: 78,
        reasoning: 'Evidence varies across different testing environments and geographic baselines.',
        supportingSourceIds: ['src-dyn-2'],
        conflictingSourceIds: [],
        keyQuotes: [
          'Official governmental research findings providing structured guidance.',
        ],
        extractedByAgent: 'Evidence Analyst',
      },
    ],
    contradictions: [
      {
        id: 'cnt-dyn-1',
        topic: 'Environmental / Operational Context',
        claimA: 'Nature trial indicates high consistency in controlled laboratory settings.',
        sourceAId: 'src-dyn-1',
        claimB: 'Field deployment report notes 12% variance under extreme external conditions.',
        sourceBId: 'src-dyn-2',
        explanation: 'Controlled laboratory results show higher consistency than real-world uncontrolled environments.',
        impactOnConfidence: -10,
      },
    ],
    recommendations: [
      'Focus implementation on core verified parameters documented in Nature peer-reviewed studies.',
      'Monitor ongoing empirical trials for long-term outcome validation.',
    ],
    methodologyNotes: 'Dynamic execution completed across 9 specialized autonomous agents.',
  };
}
